In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

importing data

In [4]:
df = pd.read_csv('creditcard.csv')
df.head(10)

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   
5   2.0 -0.425966  0.960523  1.141109 -0.168252  0.420987 -0.029728  0.476201   
6   4.0  1.229658  0.141004  0.045371  1.202613  0.191881  0.272708 -0.005159   
7   7.0 -0.644269  1.417964  1.074380 -0.492199  0.948934  0.428118  1.120631   
8   7.0 -0.894286  0.286157 -0.113192 -0.271526  2.669599  3.721818  0.370145   
9   9.0 -0.338262  1.119593  1.044367 -0.222187  0.499361 -0.246761  0.651583   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   
5  0.260314 -0.568671  ... -0.208254 -0.559825 -0.026398 -0.371427 -0.232794   
6  0.081213  0.464960  ... -0.167716 -0.270710 -0.154104 -0.780055  0.750137   
7 -3.807864  0.615375  ...  1.943465 -1.015455  0.057504 -0.649709 -0.415267   
8  0.851084 -0.392048  ... -0.073425 -0.268092 -0.204233  1.011592  0.373205   
9  0.069539 -0.736727  ... -0.246914 -0.633753 -0.120794 -0.385050 -0.069733   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  
5  0.105915  0.253844  0.081080    3.67      0  
6 -0.257237  0.034507  0.005168    4.99      0  
7 -0.051634 -1.206921 -1.085339   40.80      0  
8 -0.384157  0.011747  0.142404   93.20      0  
9  0.094199  0.246219  0.083076    3.68      0  

[10 rows x 31 columns]

In [3]:
X = df.iloc[:,:-1].values
print(X)
y = df.iloc[:,-1].values
print(y)

[[ 0.00000000e+00 -1.35980713e+00 -7.27811733e-02 ...  1.33558377e-01
  -2.10530535e-02  1.49620000e+02]
 [ 0.00000000e+00  1.19185711e+00  2.66150712e-01 ... -8.98309914e-03
   1.47241692e-02  2.69000000e+00]
 [ 1.00000000e+00 -1.35835406e+00 -1.34016307e+00 ... -5.53527940e-02
  -5.97518406e-02  3.78660000e+02]
 ...
 [ 1.72788000e+05  1.91956501e+00 -3.01253846e-01 ...  4.45477214e-03
  -2.65608286e-02  6.78800000e+01]
 [ 1.72788000e+05 -2.40440050e-01  5.30482513e-01 ...  1.08820735e-01
   1.04532821e-01  1.00000000e+01]
 [ 1.72792000e+05 -5.33412522e-01 -1.89733337e-01 ... -2.41530880e-03
   1.36489143e-02  2.17000000e+02]]
[0 0 0 ... 0 0 0]


In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

1/Logistic Regression model

In [8]:
#importing logistic regression model
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(random_state = 0)
model.fit(X_train, y_train)

C:\Users\THINKPAD\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

In [9]:
#prediction
y_pred=model.predict(X_test)
y_pred2=model.predict(X_train)

In [10]:
from sklearn.metrics import accuracy_score
#calculating accuracy
score_train = accuracy_score(y_train, y_pred2)
print('\n Score de performance entrainnement:')
print(score_train)

score_test = accuracy_score(y_test, y_pred)
print('\n Score de performance test:')
print(score_test)


 Score de performance entrainnement:
0.9989729860211987

 Score de performance test:
0.9988939995084443


In [11]:
#calculiting confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print('\nMatrice de confusion :' )
print(cm)


Matrice de confusion :
[[56848    27]
 [   36    51]]


2/SVM model

In [12]:
from sklearn import svm
model2 = svm.SVC(C=100, kernel='linear')
model2.fit(X_train, y_train)

SVC(C=100, kernel='linear')

In [13]:
#prediction
y_pred=model2.predict(X_test)
y_pred2=model2.predict(X_train)

In [14]:
from sklearn.metrics import accuracy_score
#calculating accuracy
score_train = accuracy_score(y_train, y_pred2)
print('\n Score de performance entrainnement:')
print(score_train)

score_test = accuracy_score(y_test, y_pred)
print('\n Score de performance test:')
print(score_test)


 Score de performance entrainnement:
0.9985999253878733

 Score de performance test:
0.998735999438222


In [15]:
#calculiting confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print('\nMatrice de confusion :' )
print(cm)


Matrice de confusion :
[[56861    14]
 [   58    29]]


3/KNN model

In [16]:
from sklearn.neighbors import KNeighborsClassifier
model3= KNeighborsClassifier(n_neighbors=3)
model3.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [18]:
#prediction
y_pred=model3.predict(X_test)
y_pred2=model3.predict(X_train)

In [19]:
from sklearn.metrics import accuracy_score
#calculating accuracy
score_train = accuracy_score(y_train, y_pred2)
print('\n Score de performance entrainnement:')
print(score_train)

score_test = accuracy_score(y_test, y_pred)
print('\n Score de performance test:')
print(score_test)


 Score de performance entrainnement:
0.9986174811823828

 Score de performance test:
0.9985077771145676


In [20]:
#calculiting confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print('\nMatrice de confusion :' )
print(cm)


Matrice de confusion :
[[56874     1]
 [   84     3]]
